### PR TITLE
Oleg.Mikhailov

### PR DESCRIPTION
**Pull request by MikhailovOlegM**
Homework 28

### CODE REVIEW

**Comment by MikhailovOlegM** [comment]
I will fixed this

**Comment by parkhomenko** [comment]
Sure, seems to be a triffle with checkstyle

**Comment by MikhailovOlegM** [comment]
@parkhomenko No, I accidentally sent an unfinished 29 task:)
I will finish them today

**Review by parkhomenko — APPROVED** [review]
Great. It's good you don't forget about tests.

**Pull request merged**
